import os
import random
import uuid
from datetime import datetime, timedelta

from faker import Faker
from dotenv import load_dotenv

# Import database functions
# Ensure we are running from backend directory or set pythonpath
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from database import (
    get_supabase,
    create_patient,
    create_appointment,
    create_visit,
    create_document,
    create_consult_session,
    create_prescription,
    create_note
)

load_dotenv()

fake = Faker()

def seed_data():
    print("🌱 Starting database seeding...")
    
    supabase = get_supabase()
    
    # Create Patients
    patients = []
    print("Creating patients...")
    for _ in range(10):  # Create 10 patients
        gender = random.choice(["Male", "Female", "Other"])
        patient_data = {
            "name": fake.name() if gender != "Male" else fake.name_male(), # Simple way, fake.name() is fine too
            "age": random.randint(18, 90),
            "gender": gender,
            "height_cm": random.randint(150, 200),
            "weight_kg": random.randint(50, 120),
            "conditions": random.sample(["Hypertension", "Diabetes", "Asthma", "Arthritis", "Anxiety", "Migraine"], k=random.randint(0, 3)),
            "medications": random.sample(["Lisinopril", "Metformin", "Ibuprofen", "Amoxicillin", "Atorvastatin"], k=random.randint(0, 3)),
            "allergies": random.sample(["Peanuts", "Penicillin", "Dust Mites", "Pollen", "Latex"], k=random.randint(0, 2)),
            "vitals": {
                "bp_systolic": random.randint(110, 160),
                "bp_diastolic": random.randint(70, 100),
                "spo2": random.randint(95, 100),
                "heart_rate": random.randint(60, 100),
                "temperature_f": round(random.uniform(97.0, 99.5), 1)
            }
        }
        
        try:
            p = create_patient(patient_data)
            patients.append(p)
            print(f"  + Created patient: {p.get('name')} (ID: {p.get('id')})")
        except Exception as e:
            print(f"  ! Error creating patient: {e}")

    if not patients:
        print("❌ No patients created. Aborting.")
        return

    # Create Data for each Patient
    for p in patients:
        p_id = p["id"]
        
        # 1. Appointments (Past and Future)
        for _ in range(random.randint(1, 4)):
            is_past = random.choice([True, False])
            if is_past:
                date = datetime.now() - timedelta(days=random.randint(1, 30))
                status = "completed"
            else:
                date = datetime.now() + timedelta(days=random.randint(1, 14))
                status = "scheduled"
            
            appt_data = {
                "patient_id": p_id,
                "start_time": date.isoformat(),
                "status": status,
                "reason": random.choice([
                    "Annual physical check-up",
                    "Persistent cough and cold symptoms",
                    "Follow-up for hypertension management",
                    "Consultation for back pain",
                    "Routine blood work analysis",
                    "Skin rash evaluation",
                    "Prescription renewal for asthma",
                    "Joint pain in knees",
                    "Headache and migraine consultation",
                    "Digestive issues and stomach pain",
                    "Flu vaccination",
                    "Diabetes monitoring check-up",
                    "Allergy symptoms assessment",
                    "Sore throat and fever",
                    "Anxiety and stress management",
                    "Insomnia and sleep disorder maintainance",
                    "Weight management consultation",
                    "Ear infection check",
                    "Eye irritation and vision check",
                    "General fatigue and weakness"
                ]),
                # ID is generated by DB default if not provided, but main.py generates it. 
                # Let's let DB generate it or generate one here if needed.
                # schema.sql has default.
            }
            create_appointment(appt_data)
            
        # 2. Visits (Past)
        for _ in range(random.randint(0, 3)):
            visit_date = datetime.now() - timedelta(days=random.randint(0, 2)*365 + random.randint(1, 365))
            visit_data = {
                "patient_id": p_id,
                "visit_time": visit_date.isoformat(),
                "summary_ai": fake.paragraph(nb_sentences=3),
                "doctor_notes_text": fake.paragraph(nb_sentences=5),
            }
            create_visit(visit_data)

        # 3. Documents
        for _ in range(random.randint(0, 3)):
            doc_data = {
                "patient_id": p_id,
                "title": f"{random.choice(['Lab Report', 'X-Ray', 'Referral Letter', 'Prescription'])} - {fake.date()}",
                "doc_type": random.choice(["report", "image", "referral", "prescription"]),
                "extracted_text": fake.text(max_nb_chars=1000)
            }
            create_document(doc_data)

        # 4. Consult Sessions
        for _ in range(random.randint(0, 2)):
            start = datetime.now() - timedelta(days=random.randint(1, 60))
            end = start + timedelta(minutes=random.randint(10, 30))
            consult_data = {
                "patient_id": p_id,
                "started_at": start.isoformat(),
                "ended_at": end.isoformat(),
                "transcript_text": fake.text(max_nb_chars=2000),
                "soap_note": {
                    "subjective": fake.paragraph(),
                    "objective": fake.paragraph(),
                    "assessment": fake.paragraph(),
                    "plan": fake.paragraph()
                },
                "insights_json": {"summary": fake.sentence()}
            }
            create_consult_session(consult_data)

        # 5. Prescriptions
        for _ in range(random.randint(0, 2)):
            presc_data = {
                "patient_id": p_id,
                "diagnosis": fake.sentence(nb_words=3),
                "notes": fake.sentence(),
                "medications": [
                    {
                        "name": random.choice(["Amoxicillin", "Ibuprofen", "Lisinopril"]),
                        "dosage": "500mg",
                        "frequency": "Twice daily",
                        "duration": "7 days"
                    }
                ]
            }
            create_prescription(presc_data)

        # 6. Notes
        for _ in range(random.randint(0, 3)):
            note_data = {
                "patient_id": p_id,
                "content": fake.paragraph(),
                "note_type": random.choice(["general", "phone_call", "observation"])
            }
            create_note(note_data)

        # 7. AI Intake & Differential (Using raw supabase client for these as helper might not exist or be simple)
        # database.py does not have create functions for ai_intake or differential?
        # Checked database.py: get_ai_intake_summary exists, but create_... does not seem to serve it (only getters).
        # Ah, looking at the file again...
        # database.py has: create_patient, create_appointment, create_visit, create_document, create_consult_session, create_prescription, create_note.
        # It DOES NOT have create_ai_intake_summary or create_differential_diagnosis.
        # So I will use the supabase client directly for those.
        
        supabase.table("ai_intake_summaries").insert({
            "patient_id": p_id,
            "summary_text": fake.paragraph(nb_sentences=5)
        }).execute()
        
        supabase.table("differential_diagnoses").insert({
            "patient_id": p_id,
            "condition_name": fake.word(),
            "match_pct": random.randint(50, 99),
            "rationale": fake.sentence()
        }).execute()
        
        supabase.table("report_insights").insert({
            "patient_id": p_id,
            "insight_text": fake.paragraph()
        }).execute()

    print("✅ Seeding complete!")

if __name__ == "__main__":
    seed_data()
